CODE/InternetBandwidth/InternetBandwidth/InternetBandwidth/urls.py
from django.contrib import admin
from django.urls import path
from users import views as u1
from admins import views as a1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',u1.index1,name='index1'),
  
    path("userRegister", u1.UserRegister, name="userRegister"),
    path('userlogin',u1.UserLoginCheck,name='userlogin'),
    path('userbase',u1.userbase,name='userbase'),
    path('usrViewData/', u1.usrViewData, name='usrViewData'),
    path('usrEDAData/', u1.usrEDAData, name='usrEDAData'),
    path('usrMachineLearning/', u1.usrMachineLearning, name='usrMachineLearning'),
    path('usrPredictForm/', u1.usrPredictForm, name='usrPredictForm'),
    
    
    path('adminlogin',a1.adminlog,name='adminlogin'),
    path('AdminHome',a1.AdminHome,name='AdminHome'),
    path("ViewRegisteredUsers", a1.ViewRegisteredUsers, name="ViewRegisteredUsers"),
    path("AdminActivaUsers/", a1.AdminActivaUsers, name="AdminActivaUsers"),
    path("mlresults/", a1.mlresults, name='mlresults'),
]

CODE/InternetBandwidth/InternetBandwidth/urls.py
from django.contrib import admin
from django.urls import path
from users import views as u1
from admins import views as a1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',u1.index1,name='index1'),
  
    path("userRegister", u1.UserRegister, name="userRegister"),
    path('userlogin',u1.UserLoginCheck,name='userlogin'),
    path('userbase',u1.userbase,name='userbase'),
    path('usrViewData/', u1.usrViewData, name='usrViewData'),
    path('usrEDAData/', u1.usrEDAData, name='usrEDAData'),
    path('usrMachineLearning/', u1.usrMachineLearning, name='usrMachineLearning'),
    path('usrPredictForm/', u1.usrPredictForm, name='usrPredictForm'),
    
    
    path('adminlogin',a1.adminlog,name='adminlogin'),
    path('AdminHome',a1.AdminHome,name='AdminHome'),
    path("ViewRegisteredUsers", a1.ViewRegisteredUsers, name="ViewRegisteredUsers"),
    path("AdminActivaUsers/", a1.AdminActivaUsers, name="AdminActivaUsers"),
    path("mlresults/", a1.mlresults, name='mlresults'),
]

CODE/InternetBandwidth/InternetBandwidth/admins/models.py
from django.db import models

# Create your models here.

CODE/InternetBandwidth/InternetBandwidth/users/models.py
from django.db import models



# Create your models here.
class UserRegistrationModel(models.Model):
    name = models.CharField(max_length=100)
    loginid = models.CharField(unique=True, max_length=100)
    password = models.CharField(max_length=100)
    mobile = models.CharField(unique=True, max_length=100)
    email = models.CharField(unique=True, max_length=100)
    locality = models.CharField(max_length=100)
    address = models.CharField(max_length=1000)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    status = models.CharField(max_length=100)

    def __str__(self):
        return self.loginid

    class Meta:
        db_table = 'UserRegistrations'

CODE/InternetBandwidth/InternetBandwidth/users/forms.py
from django import forms
from .models import UserRegistrationModel


class UserRegistrationForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'pattern': '[a-zA-Z]+'}), required=True, max_length=100)
    loginid = forms.CharField(widget=forms.TextInput(attrs={'pattern': '[a-zA-Z]+'}), required=True, max_length=100)
    password = forms.CharField(widget=forms.PasswordInput(attrs={'pattern': '(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}',
                                                                 'title': 'Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters'}),
                               required=True, max_length=100)
    mobile = forms.CharField(widget=forms.TextInput(attrs={'pattern': '[56789][0-9]{9}'}), required=True,
                             max_length=100)
    email = forms.CharField(widget=forms.TextInput(attrs={'pattern': '[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$'}),
                            required=True, max_length=100)
    locality = forms.CharField(widget=forms.TextInput(), required=True, max_length=100)
    address = forms.CharField(widget=forms.Textarea(attrs={'rows': 4, 'cols': 22}), required=True, max_length=250)
    city = forms.CharField(widget=forms.TextInput(
        attrs={'autocomplete': 'off', 'pattern': '[A-Za-z ]+', 'title': 'Enter Characters Only '}), required=True,
        max_length=100)
    state = forms.CharField(widget=forms.TextInput(
        attrs={'autocomplete': 'off', 'pattern': '[A-Za-z ]+', 'title': 'Enter Characters Only '}), required=True,
        max_length=100)
    status = forms.CharField(widget=forms.HiddenInput(), initial='waiting', max_length=100)

    class Meta():
        model = UserRegistrationModel
        fields = '__all__'

CODE/InternetBandwidth/InternetBandwidth/admins/views.py
from django.shortcuts import render
from django.contrib import messages
from users.models import UserRegistrationModel

# Create your views here.

def adminlog(request):
    if request.method == 'POST':
        usrid = request.POST.get('loginname')
        pswd = request.POST.get('pswd')
        print("User ID is = ", usrid)
        if usrid == 'admin' and pswd == 'admin':
            return render(request, 'admins/AdminHome.html')
        elif usrid == 'Admin' and pswd == 'Admin':
            return render(request, 'admins/AdminHome.html')
        else:
            messages.success(request, 'Please Check Your Login Details')
    return render(request, 'adminlogin.html',)


def AdminHome(request):
    return render(request, 'admins/AdminHome.html',{})


def ViewRegisteredUsers(request):
    data = UserRegistrationModel.objects.all()
    return render(request, 'admins/viewRegisteredUsers.html', {'data': data})

def AdminActivaUsers(request):
    if request.method == 'GET':
        id = request.GET.get('uid')
        status = 'activated'
        print("PID = ", id, status)
        UserRegistrationModel.objects.filter(id=id).update(status=status)
        data = UserRegistrationModel.objects.all()
        return render(request, 'admins/viewRegisteredUsers.html', {'data': data})


def mlresults(request):
    from users.utility.MachineLearning import startProcess
    df_dt, dt_acc, rf_df, rf_acc, knn_df, knn_acc = startProcess()
    return render(request, 'admins/MLResults.html',
                  {'df_dt': df_dt, 'dt_acc': dt_acc, 'rf_df': rf_df, 'rf_acc': rf_acc, 'knn_df': knn_df,
                   'knn_acc': knn_acc})

CODE/InternetBandwidth/InternetBandwidth/users/views.py
from django.shortcuts import render, HttpResponse
from django.contrib import messages
from tenacity import retry_if_not_exception_message

from .forms import UserRegistrationForm
from .models import UserRegistrationModel
from django.conf import settings
import pandas as pd
import os


# Create your views here.
def UserRegister(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            form = UserRegistrationForm()
            return render(request, 'userregister.html', {'form': form})
    else:
        form = UserRegistrationForm()
        return render(request, 'userregister.html', {'form': form})


def UserLoginCheck(request):
    if request.method == "POST":
        loginid = request.POST.get('loginname')
        pswd = request.POST.get('pswd')
        print("Login ID = ", loginid, ' Password = ', pswd)
        try:
            check = UserRegistrationModel.objects.get(loginid=loginid, password=pswd)
            status = check.status
            print('Status is = ', status)
            if status == "activated":
                request.session['id'] = check.id
                request.session['loggeduser'] = check.name
                request.session['loginid'] = loginid
                request.session['email'] = check.email
                print("User id At", check.id, status)
                return render(request, 'users/UserHome.html', {})
            else:
                messages.success(request, 'Your Account Not at activated')
                return render(request, 'userlogin.html')
        except Exception as e:
            print('Exception is ', str(e))
            pass
        messages.success(request, 'Invalid Login id and password')
    return render(request, 'userlogin.html', {})


# Create your views here.
def index1(request):
    return render(request, 'base.html')


def userbase(request):
    return render(request, 'users/UserHome.html')


def usrViewData(request):
    path = os.path.join(settings.MEDIA_ROOT, 'Punedata.csv')
    df = pd.read_csv(path)
    df = df.to_html(index=False)
    return render(request, 'users/viewDataset.html', {'data': df})


def usrEDAData(request):
    # from .utility.edaanalysis import startEda
    # obj = startEda()
    return render(request, 'users/edanalysis.html', {})


def usrMachineLearning(request):
    from .utility.MachineLearning import startProcess
    df_dt, dt_acc, rf_df, rf_acc, knn_df, knn_acc = startProcess()
    return render(request, 'users/usrMLResults.html',
                  {'df_dt': df_dt, 'dt_acc': dt_acc, 'rf_df': rf_df, 'rf_acc': rf_acc, 'knn_df': knn_df,
                   'knn_acc': knn_acc})


def usrPredictForm(request):
    path = os.path.join(settings.MEDIA_ROOT, 'Punedata.csv')
    df = pd.read_csv(path)
    lac = df['LAC'].values
    if request.method=='POST':
        from .utility.userPredictions import get_user_input
        lac = request.POST.get('laccode')
        result = get_user_input(lac)
        msg = f'In The LAC {lac} the Internet Consumption {result} GB (lacks)'

        return render(request, 'users/predictForm.html', {'lac': lac,'msg':msg})

    else:

        return render(request,'users/predictForm.html',{'lac': lac})

CODE/InternetBandwidth/InternetBandwidth/templates/adminlogin.html
{% extends 'base.html' %}
{% block content %}

<style>
    #id_username{
        border-radius: 10px;
        width: 400px;
    
        margin-left: 10px;
     
   }
  
     
   
   #id_password{
        border-radius: 10px;
        margin-left: 5px;
        width: 400px;
     
   }
</style>



    <section class="txt-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="aligncenter">
                        <h2 class="row justify-content-center text-dark"><i class="fa fa-sign-in-alt"
                                                                            style=" margin-top:50px;">&nbsp;admin
                            Log In</i></h2>
                        <form  method="post" novalidate>
                            {%csrf_token%}
    
                            <div id="div_id_username" class="form-group"><label for="id_username" class=" requiredField">
                                Username<span class="asteriskField">*</span> </label>
                                <div><input type="text" name="loginname" required autofocus autocapitalize="none"
                                            autocomplete="username" maxlength="150" class="textinput textInput form-control"
                                            required id="id_username"></div>
                            </div>
                            <div id="div_id_password" class="form-group"><label for="id_password" class=" requiredField">
                                Password<span class="asteriskField">*</span> </label>
                                <div><input type="password" name="pswd" required autocomplete="current-password"
                                            class="textinput textInput form-control" required id="id_password"></div>
                            </div>
    
                            <button type="submit" class="btn btn-dark mb-2">Login</button>
    
                        </form>
                        {% if messages %}
                        {% for message in messages %}
                        <font color='RED'> {{ message }}</font>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>
{% endblock %}

CODE/InternetBandwidth/InternetBandwidth/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Internet Bandwidth</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: MeFamily - v4.9.1
  * Template URL: https://bootstrapmade.com/family-multipurpose-html-bootstrap-template-free/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>
<style>
  body{
    background-image: url('https://images.pexels.com/photos/3184357/pexels-photo-3184357.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1');
    background-size: cover;
    background-repeat:no-repeat;

    

  }
  </style

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container d-flex align-items-center justify-content-between">

      <h1 class="logo"><a href="index.html">Internet Bandwidth</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="{% url 'index1' %}">Home</a></li>
          <li><a href="{% url 'userlogin' %}">user</a></li>
          <li><a href="{% url 'adminlogin' %}">admin</a></li>
          <li><a href="{% url 'userRegister' %}">register</a></li>
    
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  {% block content %}
  {% endblock %}


  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

CODE/InternetBandwidth/InternetBandwidth/templates/userlogin.html
{% extends 'base.html' %}
{% block content %}


<style>
    #id_username{
        border-radius: 10px;
        width: 400px;
    
        margin-left: 10px;
     
   }
  
     
   
   #id_password{
        border-radius: 10px;
        margin-left: 5px;
        width: 400px;
     
   }
</style>

    <section class="txt-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="aligncenter">
                        <h2 class="row justify-content-center text-dark"><i class="fa fa-sign-in-alt"
                                                                            style=" margin-top:50px">&nbsp;User
                            Log In</i></h2>
                        <form  method="post" novalidate>
                            {%csrf_token%}
    
                            <div id="div_id_username" class="form-group"><label for="id_username" class=" requiredField">
                                Username<span class="asteriskField">*</span> </label>
                                <div><input type="text" name="loginname" required autofocus autocapitalize="none"
                                            autocomplete="username" maxlength="150" class="textinput textInput form-control"
                                            required id="id_username"></div>
                            </div>
                            <div id="div_id_password" class="form-group"><label for="id_password" class=" requiredField">
                                Password<span class="asteriskField">*</span> </label>
                                <div><input type="password" name="pswd" required autocomplete="current-password"
                                            class="textinput textInput form-control" required id="id_password"></div>
                            </div>
    
                            <button type="submit" class="btn btn-dark mb-2">Login</button>
    
                        </form>
                        {% if messages %}
                        {% for message in messages %}
                        <font color='RED'> {{ message }}</font>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>
{% endblock %}

CODE/InternetBandwidth/InternetBandwidth/templates/userregister.html
{% extends 'base.html' %}
{% block content %}
<style>
     .mar{
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
          margin-top: 100px;
          color: black;
          font-weight: 1000px;
          font-size: 23px;
          
     }
     #id_name{
          border-radius: 10px;
          align-self: center;
          margin-left: 10px;
       
     }
     #id_loginid{
          border-radius: 10px;
          align-self: center;
          margin-left: 8px;
       
     }
     #id_password{
          border-radius: 10px;
          margin-left: 5px;
       
     }
     #id_mobile{
          border-radius: 10px;
          margin-left: 10px;
       
     }
   
       
     
     #id_email{
          border-radius: 10px;
          margin-left: 10px;
          color: whitesmoke;
       
     }
     #id_locality{
          border-radius: 10px;
          margin-left: 10px;
       
     }
     #id_address{
          border-radius: 20px;
          height: 30px;
          margin-left: 10px;
         
       
     }
     #id_city{
          border-radius: 10px;
          margin-left: 10px;
       
     }
     #id_state{
          border-radius: 10px;
          margin-left: 10px;
       
     }
     label{
          color: hwb(160 9% 90%);
     }
</style>

     <form  method="post" class="mar">
          <h1>create account</h1>
          {% csrf_token %}
          {{form.as_p}}
          <button type="submit">register</button>
          </form>

          
</html>
{% endblock %}